//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everyday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int idClient { get; set; }
        public string nameClient { get; set; }
        public string lastnameClient { get; set; }
        public string nitClient { get; set; }
        public string addressClient { get; set; }
        public string phone { get; set; }
        public int idPais { get; set; }
        public int idDepa { get; set; }
        public int idCity { get; set; }
        public int idUser { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
