//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everyday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesVenta
    {
        public int idDetail { get; set; }
        public int idVent { get; set; }
        public int iProd { get; set; }
        public Nullable<decimal> price { get; set; }
        public int quantity { get; set; }
        public decimal subTotal { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual Venta Venta { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
