//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everyday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int idTarjet { get; set; }
        public int numTarjet { get; set; }
        public int codeTarjet { get; set; }
        public int cvv { get; set; }
        public string nameTarjet { get; set; }
        public decimal saldo { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime expireDate { get; set; }
        public string state { get; set; }
        public int idUser { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
