//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everyday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public int idType { get; set; }
        public string nameType { get; set; }
        public int idProd { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
